// <auto-generated />
using LabProcess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabProcess.Migrations
{
    [DbContext(typeof(dbcontext))]
    [Migration("20210502215136_entities")]
    partial class entities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("raw", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("keyNew")
                        .HasColumnType("longtext");

                    b.Property<string>("keyOld")
                        .HasColumnType("longtext");

                    b.Property<string>("nameNew")
                        .HasColumnType("longtext");

                    b.Property<string>("nameOld")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("raws");
                });
#pragma warning restore 612, 618
        }
    }
}
